In [2]:
from requests import Request, Session
from requests.exceptions import ConnectionError, Timeout, TooManyRedirects
import json

url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest' 
#Original Sandbox Environment: 'https://sandbox-api.coinmarketcap.com/v1/cryptocurrency/listings/latest'
parameters = {
  'start':'1',
  'limit':'5000',
  'convert':'USD'
}
headers = {
  'Accepts': 'application/json',
  'X-CMC_PRO_API_KEY': '0ad53085-1cb2-4eb8-ad9e-3ffbd7e56509',
}

session = Session()
session.headers.update(headers)

try:
  response = session.get(url, params=parameters)
  data = json.loads(response.text)
  #print(data)
except (ConnectionError, Timeout, TooManyRedirects) as e:
  print(e)

In [3]:
type(data)

dict

In [6]:
import pandas as pd


#This allows you to see all the columns, not just like 15
pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)

In [7]:
#This normalizes the data and makes it all pretty in a dataframe

pd.json_normalize(data['data'])

,id,name,symbol,slug,num_market_pairs,date_added,tags,max_supply,circulating_supply,total_supply,infinite_supply,platform,cmc_rank,self_reported_circulating_supply,self_reported_market_cap,tvl_ratio,last_updated,quote.USD.price,quote.USD.volume_24h,quote.USD.volume_change_24h,quote.USD.percent_change_1h,quote.USD.percent_change_24h,quote.USD.percent_change_7d,quote.USD.percent_change_30d,quote.USD.percent_change_60d,quote.USD.percent_change_90d,quote.USD.market_cap,quote.USD.market_cap_dominance,quote.USD.fully_diluted_market_cap,quote.USD.tvl,quote.USD.last_updated,platform.id,platform.name,platform.symbol,platform.slug,platform.token_address
0,1,Bitcoin,BTC,bitcoin,11047,2010-07-13T00:00:00.000Z,"[mineable, pow, sha-256, store-of-value, state...",2.100000e+07,1.970045e+07,19700453,False,NaN,1,NaN,NaN,NaN,2024-05-19T16:50:00.000Z,6.684589e+04,1.651996e+10,-17.6259,-0.010141,-0.069293,8.567878,4.090227,5.929057,28.355423,1.316894e+12,54.7067,1.403764e+12,NaN,2024-05-19T16:50:00.000Z,NaN,NaN,NaN,NaN,NaN
1,1027,Ethereum,ETH,ethereum,8950,2015-08-07T00:00:00.000Z,"[pos, smart-contracts, ethereum-ecosystem, coi...",NaN,1.201243e+08,120124343.17646,True,NaN,2,NaN,NaN,NaN,2024-05-19T16:49:00.000Z,3.069606e+03,8.009018e+09,-23.8426,-0.149384,-1.395936,4.509021,-0.073055,-5.517956,5.143909,3.687344e+11,15.3229,3.687344e+11,NaN,2024-05-19T16:49:00.000Z,NaN,NaN,NaN,NaN,NaN
2,825,Tether USDt,USDT,tether,85865,2015-02-25T00:00:00.000Z,"[stablecoin, asset-backed-stablecoin, avalanch...",NaN,1.114349e+11,114086550454.3862,True,NaN,3,NaN,NaN,NaN,2024-05-19T16:49:00.000Z,1.000104e+00,3.541955e+10,-18.8467,0.003548,-0.017364,0.035007,-0.038389,0.022816,0.023496,1.114465e+11,4.6312,1.140984e+11,NaN,2024-05-19T16:49:00.000Z,1027.0,Ethereum,ETH,ethereum,0xdac17f958d2ee523a2206206994597c13d831ec7
3,1839,BNB,BNB,bnb,2162,2017-07-25T00:00:00.000Z,"[marketplace, centralized-exchange, payments, ...",NaN,1.475863e+08,147586311.844414,False,NaN,4,NaN,NaN,NaN,2024-05-19T16:49:00.000Z,5.756118e+02,1.305295e+09,-4.1801,-0.214289,-0.308802,-3.290423,3.141070,11.124491,62.702733,8.495242e+10,3.5304,8.495242e+10,NaN,2024-05-19T16:49:00.000Z,NaN,NaN,NaN,NaN,NaN
4,5426,Solana,SOL,solana,660,2020-04-10T00:00:00.000Z,"[pos, platform, solana-ecosystem, cms-holdings...",NaN,4.489140e+08,576325109.361397,True,NaN,5,NaN,NaN,NaN,2024-05-19T16:49:00.000Z,1.684748e+02,2.137238e+09,-18.5324,0.390142,-1.395302,15.682408,15.405271,-0.399212,48.721363,7.563067e+10,3.1438,9.709623e+10,NaN,2024-05-19T16:49:00.000Z,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,17479,Artmeta,MART,artmeta,5,2022-01-19T14:52:37.000Z,"[collectibles-nfts, metaverse, polygon-ecosystem]",NaN,0.000000e+00,0,False,NaN,4994,NaN,NaN,NaN,2024-05-19T16:49:00.000Z,6.275461e-03,1.328549e+04,-3.6090,0.178976,1.724933,8.782880,-0.802329,-18.501550,-26.672950,0.000000e+00,0.0000,0.000000e+00,NaN,2024-05-19T16:49:00.000Z,3890.0,Polygon,MATIC,polygon,0xDcfF29b7bd211Aaef6E4a3989e4d3F732cF5b4b6
4996,11322,Mobius Finance,MOT,mobius-finance,8,2021-08-19T00:00:00.000Z,[],NaN,0.000000e+00,11919002,False,NaN,4996,1.191900e+07,1.523882e+04,NaN,2024-05-19T16:49:00.000Z,1.278532e-03,1.324977e+04,-1.6986,-0.321891,-4.985875,6.687340,8.432952,12.569590,2.807660,0.000000e+00,0.0000,1.523882e+04,NaN,2024-05-19T16:49:00.000Z,1027.0,Ethereum,ETH,ethereum,0x1E02cdbbA6729B6470de81Ad4D2cCA4c514521b9
4997,11421,Marnotaur,TAUR,marnotaur,1,2021-08-26T21:44:32.000Z,[],1.500000e+08,0.000000e+00,0,False,NaN,4997,1.050000e+07,1.111596e+04,NaN,2024-05-19T16:49:00.000Z,1.058663e-03,1.320369e+04,-7.7106,-0.061433,-9.469453,-3.295536,-13.054868,-31.381103,-12.880883,0.000000e+00,0.0000,1.587995e+05,NaN,2024-05-19T16:49:00.000Z,1027.0,Ethereum,ETH,ethereum,0xF71288618F919FF0A779c757489A8B2e45925dDd
4998,25184,ScapesMania,MANIA,scapesmania,7,2023-05-11T02:52:03.000Z,[gaming],4.000000e+09,0.000000e+00,4000000000,False,NaN,4998,1.680000e+09,4.952577e+06,NaN,2024-05-19T16:49:00.000Z,2.947963e-03,1.315865e+04,-61.0893,0.069785,0.824135,-22.350917,-47.588656,-49.593885,-65.755402,0.000000e+00,0.0000,1.179185e+07,NaN,2024-05-19T16:49:00.000Z,1839.0,BNB Smart Chain (BEP20),BNB,bnb,0xAB4E026a2f6F6265C29BBb4C565E66968E3d4962
4999,30586,Book of Pepe,BOPE,book-of-pepe,1,2024-04-12T07:18:57.000Z,[memes],4.098300e+11,0.000000e+00,409830000000,False,NaN,5077,4.098300e+11,2.660450e+05,NaN,2024-05-19T16:49:00.000Z,6.491593e-07,1.155150e+04,-16.8825,4.608426,-4.955115,-2.315799,-57.493268,-74.138414,-74.138414,0.000000e+00,0.0000,2.660450e+05,NaN,2024-05-19T16:49:00.000Z,1027.0,Ethereum,ETH,ethereum,0x599955aa9fbc197a1b717d8da6a7012cafe70ab3